### ISSUE TITLE
Swift 버전은 없나요?

### ISSUE THREAD

**Issue by yunchiri** [adfit/adfit-ios-sdk#1]
Swift 버전은 없나요?

**Comment by harange** [comment]
Swift는 아직 대응 전이고 내년에 대응 계획이 있습니다.

**Comment by yunchiri** [comment]
그럼 지금 쓰려면 그냥 브릿지헤더만들어서 쓰면되죠?

그렇게 한번도 안써봐서요^^;;

**Comment by harange** [comment]
내부 구조 변경 이후 브릿지 헤더 방식으로 사용이 가능합니다.

**Comment by yunchiri** [comment]
![monosnap 2016-11-20 18-29-22](https://cloud.githubusercontent.com/assets/1159660/20461874/59a56028-af4f-11e6-9c5f-dedcf291b361.png)

이거  lib.1.2.5.dynlib 파일이 없는데 뭐추가하면되나요?

지금 브리짓헤더 연결해서 다했는데 광고가 안나와서
이것때문에 안나오나 싶어서 연락드립니다

![ssajul xcodeproj 2016-11-20 18-31-19](https://cloud.githubusercontent.com/assets/1159660/20461883/90254744-af4f-11e6-9f91-7087658994eb.png)

자꾸 귀찮게 해드려서 죄송해요 잘몰라서^^;;

**Comment by yunchiri** [comment]
잘됩니다 오타였습니다
감사해요!
