### ISSUE TITLE
xcode 10.2 업데이트후  image not found 문제 

### ISSUE THREAD

**Issue by kkhbbung** [adfit/adfit-ios-sdk#11]
dyld: Library not loaded: @rpath/libswiftAVFoundation.dylib
  Referenced from: /Users/dev/Library/Developer/CoreSimulator/Devices/2DA39B69-525E-4E7C-AF84-64CBDEDF0A1B/data/Containers/Bundle/Application/8EA2342D-3EDD-4142-8C1B-0C33081CB898/money.app/Frameworks/AdFitSDK.framework/AdFitSDK
  Reason: image not found
오늘 xcode업데이트후 이런문제가 발생합니다.
프레임워크는 수동설치했습니다.
샘플소스도 안됩니다.

**Comment by Kim-Deogwon** [comment]
3.0.7버전에 Xcode 10.2 대응 완료 하였습니다.  감사합니다.
