### ISSUE TITLE
크래시 공유

### ISSUE THREAD

**Issue by jangsy7883** [adfit/adfit-ios-sdk#13]
Fabric의 크래시리틱스를 통해서 AdFitSDK 에서 발생하는 것 같은 크래시가 수집되어서 공유합니다.

https://www.dropbox.com/s/wpanqqxj90zvqlo/adfit.png?dl=0

개선이 가능할까요? 확인 부탁드립니다.

**Comment by nairs77** [comment]
@jangsy7883 안녕하세요. 전달해 주신 이미지에는 callstack이 접혀 있는 이미지여서 저희가 확인이 불가능한데 혹시 callstack이 확인 가능하도록 재전달 부탁 드립니다.

**Comment by jangsy7883** [comment]
죄송합니다. 답변이 늦었습니다;;
이 내용이 도움이 되었으면 좋겠습니다. 감사합니다. 

#5. Crashed: com.kakao.biz.AdFitSDK.AdFitBannerAdView.workingQueue
0  IOKit                          0x181ea0c28 IOServiceAddInterestNotification + 44
1  UIKit                          0x18b334f5c _MatchedBatteries + 112
2  UIKit                          0x18b334f5c _MatchedBatteries + 112
3  UIKit                          0x18b334e60 -[UIDevice setBatteryMonitoringEnabled:] + 212
4  AdFitSDK                       0x1050515e4 (Missing)
5  AdFitSDK                       0x1050445c0 (Missing)
6  AdFitSDK                       0x1050451f8 (Missing)
7  AdFitSDK                       0x1050453ac (Missing)
8  AdFitSDK                       0x10501393c (Missing)
9  AdFitSDK                       0x10500da34 (Missing)
10 libdispatch.dylib              0x1815b2a54 _dispatch_call_block_and_release + 24
11 libdispatch.dylib              0x1815b2a14 _dispatch_client_callout + 16
12 libdispatch.dylib              0x1815f104c _dispatch_queue_serial_drain$VARIANT$armv81 + 520
13 libdispatch.dylib              0x1815f19bc _dispatch_queue_invoke$VARIANT$armv81 + 340
14 libdispatch.dylib              0x1815f23a8 _dispatch_root_queue_drain_deferred_wlh$VARIANT$armv81 + 384
15 libdispatch.dylib              0x1815fa4b0 _dispatch_workloop_worker_thread$VARIANT$armv81 + 640
16 libsystem_pthread.dylib        0x18185af1c _pthread_wqthread + 932
17 libsystem_pthread.dylib        0x18185ab6c start_wqthread + 4

--

#0. com.apple.main-thread
0  libsystem_kernel.dylib         0x181727568 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1817273e0 mach_msg + 72
2  CoreFoundation                 0x181bde308 __CFRunLoopServiceMachPort + 196
3  CoreFoundation                 0x181bdbed4 __CFRunLoopRun + 1424
4  CoreFoundation                 0x181afbe58 CFRunLoopRunSpecific + 436
5  GraphicsServices               0x1839a8f84 GSEventRunModal + 100
6  UIKit                          0x18b17b67c UIApplicationMain + 236
7  TestApp                   0x104362288 main + 16 (main.m:16)
8  libdyld.dylib                  0x18161856c start + 4

#1. com.vungleSDK.configController.queue
0  libsystem_kernel.dylib         0x181729818 lstat + 8
1  Foundation                     0x1825400e4 _NSFileExistsAtPath + 200
2  Foundation                     0x18253ffec -[NSFileManager fileExistsAtPath:] + 120
3  TestApp                   0x104983f4c -[VNGPersistenceManager URLForChannel:category:key:error:] + 4335222604
4  TestApp                   0x104982cc0 -[VNGPersistenceManager loadObjectWithChannel:category:key:error:] + 4335217856
5  TestApp                   0x104982948 -[VNGPersistenceManager loadObjectWithClass:key:error:] + 4335216968
6  TestApp                   0x1049d100c __38+[VNGUserConsentInfoModel sharedModel]_block_invoke + 4335538188
7  libdispatch.dylib              0x1815b2a14 _dispatch_client_callout + 16
8  libdispatch.dylib              0x1815e5178 dispatch_once_f$VARIANT$armv81 + 60
9  TestApp                   0x1049d0f6c +[VNGUserConsentInfoModel sharedModel] + 4335538028
10 TestApp                   0x1049c32fc -[VungleNetworkRequestBodyBuilder buildSUserParameters] + 4335481596
11 TestApp                   0x1049c2ad8 -[VungleNetworkRequestBodyBuilder buildRequestBody] + 4335479512
12 TestApp                   0x10498065c -[VNGNetworkManager(RequestFactory) configOperationWithBackgroundInit:complete:] + 4335208028
13 TestApp                   0x1049a2ed8 -[VungleConfigController newConfigRequestOperationFromBackgroundInit:complete:] + 4335349464
14 TestApp                   0x1049a3060 __72-[VungleConfigController fetchConfigWithBackgroundInit:completionBlock:]_block_invoke + 4335349856
15 libdispatch.dylib              0x1815b2a54 _dispatch_call_block_and_release + 24
16 libdispatch.dylib              0x1815b2a14 _dispatch_client_callout + 16
17 libdispatch.dylib              0x1815f104c _dispatch_queue_serial_drain$VARIANT$armv81 + 520
18 libdispatch.dylib              0x1815f19bc _dispatch_queue_invoke$VARIANT$armv81 + 340
19 libdispatch.dylib              0x1815f23a8 _dispatch_root_queue_drain_deferred_wlh$VARIANT$armv81 + 384
20 libdispatch.dylib              0x1815fa4b0 _dispatch_workloop_worker_thread$VARIANT$armv81 + 640
21 libsystem_pthread.dylib        0x18185af1c _pthread_wqthread + 932
22 libsystem_pthread.dylib        0x18185ab6c start_wqthread + 4

#2. Thread
0  libsystem_pthread.dylib        0x18185ab68 start_wqthread + 122

#3. Thread
0  libsystem_kernel.dylib         0x181748d80 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x18185aeec _pthread_wqthread + 884
2  libsystem_pthread.dylib        0x18185ab6c start_wqthread + 4

#4. com.apple.uikit.eventfetch-thread
0  libsystem_kernel.dylib         0x181727568 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1817273e0 mach_msg + 72
2  CoreFoundation                 0x181bde308 __CFRunLoopServiceMachPort + 196
3  CoreFoundation                 0x181bdbed4 __CFRunLoopRun + 1424
4  CoreFoundation                 0x181afbe58 CFRunLoopRunSpecific + 436
5  Foundation                     0x182531594 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 304
6  Foundation                     0x1825509ac -[NSRunLoop(NSRunLoop) runUntilDate:] + 96
7  UIKit                          0x18bce57b8 -[UIEventFetcher threadMain] + 136
8  Foundation                     0x1826330f4 __NSThread__start__ + 996
9  libsystem_pthread.dylib        0x18185c2b4 _pthread_body + 308
10 libsystem_pthread.dylib        0x18185c180 _pthread_body + 310
11 libsystem_pthread.dylib        0x18185ab74 thread_start + 4

#5. Crashed: com.kakao.biz.AdFitSDK.AdFitBannerAdView.workingQueue
0  IOKit                          0x181ea0c28 IOServiceAddInterestNotification + 44
1  UIKit                          0x18b334f5c _MatchedBatteries + 112
2  UIKit                          0x18b334f5c _MatchedBatteries + 112
3  UIKit                          0x18b334e60 -[UIDevice setBatteryMonitoringEnabled:] + 212
4  AdFitSDK                       0x1050515e4 (Missing)
5  AdFitSDK                       0x1050445c0 (Missing)
6  AdFitSDK                       0x1050451f8 (Missing)
7  AdFitSDK                       0x1050453ac (Missing)
8  AdFitSDK                       0x10501393c (Missing)
9  AdFitSDK                       0x10500da34 (Missing)
10 libdispatch.dylib              0x1815b2a54 _dispatch_call_block_and_release + 24
11 libdispatch.dylib              0x1815b2a14 _dispatch_client_callout + 16
12 libdispatch.dylib              0x1815f104c _dispatch_queue_serial_drain$VARIANT$armv81 + 520
13 libdispatch.dylib              0x1815f19bc _dispatch_queue_invoke$VARIANT$armv81 + 340
14 libdispatch.dylib              0x1815f23a8 _dispatch_root_queue_drain_deferred_wlh$VARIANT$armv81 + 384
15 libdispatch.dylib              0x1815fa4b0 _dispatch_workloop_worker_thread$VARIANT$armv81 + 640
16 libsystem_pthread.dylib        0x18185af1c _pthread_wqthread + 932
17 libsystem_pthread.dylib        0x18185ab6c start_wqthread + 4

#6. Thread
0  libsystem_pthread.dylib        0x18185ab68 start_wqthread + 122

#7. Thread
0  libsystem_kernel.dylib         0x1817480f0 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x181862f74 _pthread_cond_wait$VARIANT$armv81 + 624
2  libc++.1.dylib                 0x180dfff34 std::__1::condition_variable::__do_timed_wait(std::__1::unique_lock<std::__1::mutex>&, std::__1::chrono::time_point<std::__1::chrono::system_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > >) + 96
3  JavaScriptCore                 0x188f3cd94 std::__1::cv_status std::__1::condition_variable::wait_until<std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > >(std::__1::unique_lock<std::__1::mutex>&, std::__1::chrono::time_point<std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > > const&) + 124
4  JavaScriptCore                 0x188f3cc68 std::__1::cv_status std::__1::condition_variable_any::wait_until<std::__1::unique_lock<bmalloc::Mutex>, std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > >(std::__1::unique_lock<bmalloc::Mutex>&, std::__1::chrono::time_point<std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > > const&) + 108
5  JavaScriptCore                 0x188f3caec bmalloc::AsyncTask<bmalloc::Heap, void (bmalloc::Heap::*)()>::threadRunLoop() + 280
6  JavaScriptCore                 0x188f3cde4 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)(bmalloc::AsyncTask<bmalloc::Heap, void (bmalloc::Heap::*)()>*), bmalloc::AsyncTask<bmalloc::Heap, void (bmalloc::Heap::*)()>*> >(void*) + 44
7  libsystem_pthread.dylib        0x18185c2b4 _pthread_body + 308
8  libsystem_pthread.dylib        0x18185c180 _pthread_body + 310
9  libsystem_pthread.dylib        0x18185ab74 thread_start + 4

#8. io.answers.EventQueue (QOS: BACKGROUND)
0  libsystem_kernel.dylib         0x18172897c close + 8
1  libz.1.dylib                   0x181ae9538 gzclose_w + 188
2  TestApp                   0x1045a97ac -[ANSCompressLogOperation main] + 51 (ANSCompressLogOperation.m:51)
3  Foundation                     0x18253d4c4 -[__NSOperationInternal _start:] + 848
4  Foundation                     0x18260f894 __NSOQSchedule_f + 404
5  libdispatch.dylib              0x1815b2a14 _dispatch_client_callout + 16
6  libdispatch.dylib              0x1815ef640 _dispatch_continuation_pop$VARIANT$armv81 + 420
7  libdispatch.dylib              0x1815ee09c _dispatch_async_redirect_invoke$VARIANT$armv81 + 776
8  libdispatch.dylib              0x1815f42a4 _dispatch_root_queue_drain + 568
9  libdispatch.dylib              0x1815f4008 _dispatch_worker_thread3 + 112
10 libsystem_pthread.dylib        0x18185b06c _pthread_wqthread + 1268
11 libsystem_pthread.dylib        0x18185ab6c start_wqthread + 4

#9. Thread
0  libsystem_kernel.dylib         0x181748d80 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x18185aeec _pthread_wqthread + 884
2  libsystem_pthread.dylib        0x18185ab6c start_wqthread + 4

#10. com.twitter.crashlytics.ios.MachExceptionServer
0  TestApp                   0x1045976f8 CLSProcessRecordAllThreads + 376 (CLSProcess.c:376)
1  TestApp                   0x104597ae0 CLSProcessRecordAllThreads + 407 (CLSProcess.c:407)
2  TestApp                   0x104587464 CLSHandler + 26 (CLSHandler.m:26)
3  TestApp                   0x104582854 CLSMachExceptionServer + 446 (CLSMachException.c:446)
4  libsystem_pthread.dylib        0x18185c2b4 _pthread_body + 308
5  libsystem_pthread.dylib        0x18185c180 _pthread_body + 310
6  libsystem_pthread.dylib        0x18185ab74 thread_start + 4

#11. GAIThread
0  libsystem_kernel.dylib         0x181727568 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1817273e0 mach_msg + 72
2  CoreFoundation                 0x181bde308 __CFRunLoopServiceMachPort + 196
3  CoreFoundation                 0x181bdbed4 __CFRunLoopRun + 1424
4  CoreFoundation                 0x181afbe58 CFRunLoopRunSpecific + 436
5  Foundation                     0x182531594 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 304
6  Foundation                     0x18258356c -[NSRunLoop(NSRunLoop) run] + 88
7  TestApp                   0x104562b40 +[GAI threadMain:] + 241 (GAI.m:241)
8  Foundation                     0x1826330f4 __NSThread__start__ + 996
9  libsystem_pthread.dylib        0x18185c2b4 _pthread_body + 308
10 libsystem_pthread.dylib        0x18185c180 _pthread_body + 310
11 libsystem_pthread.dylib        0x18185ab74 thread_start + 4

#12. Thread
0  libsystem_kernel.dylib         0x181748d80 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x18185aeec _pthread_wqthread + 884
2  libsystem_pthread.dylib        0x18185ab6c start_wqthread + 4

#13. com.apple.root.default-qos
0  libsystem_kernel.dylib         0x1817275a4 semaphore_wait_trap + 8
1  libdispatch.dylib              0x1815e3ee4 _dispatch_sema4_wait$VARIANT$armv81 + 24
2  libdispatch.dylib              0x1815e4de0 _dispatch_group_wait_slow + 184
3  TestApp                   0x1048e76dc -[GADOperation resultAfterWaitingWithError:] + 130 (GADOperation.m:130)
4  TestApp                   0x1048e7888 GADLoadSDKCoreSynchronously + 35 (GADJSContextController.m:35)
5  TestApp                   0x1048fb4c0 -[GADRemoteConfigurationSource refreshWithCompletionHandler:] + 159 (GADRemoteConfigurationSource.m:159)
6  TestApp                   0x1048fb104 __47-[GADRemoteConfigurationSource refreshIfNeeded]_block_invoke + 132 (GADRemoteConfigurationSource.m:132)
7  libdispatch.dylib              0x1815b2a54 _dispatch_call_block_and_release + 24
8  libdispatch.dylib              0x1815b2a14 _dispatch_client_callout + 16
9  libdispatch.dylib              0x1815ee394 _dispatch_queue_override_invoke$VARIANT$armv81 + 700
10 libdispatch.dylib              0x1815f42a4 _dispatch_root_queue_drain + 568
11 libdispatch.dylib              0x1815f4008 _dispatch_worker_thread3 + 112
12 libsystem_pthread.dylib        0x18185b06c _pthread_wqthread + 1268
13 libsystem_pthread.dylib        0x18185ab6c start_wqthread + 4

#14. Thread
0  libsystem_kernel.dylib         0x181748d80 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x18185aeec _pthread_wqthread + 884
2  libsystem_pthread.dylib        0x18185ab6c start_wqthread + 4

#15. com.google.fira.worker
0  libsystem_kernel.dylib         0x181729860 fsync + 8
1  libsqlite3.dylib               0x18209b828 (null) + 59100
2  libsqlite3.dylib               0x18209b0dc (null) + 57232
3  libsqlite3.dylib               0x1820879ec (null) + 21904
4  libsqlite3.dylib               0x182055288 (null) + 3472
5  libsqlite3.dylib               0x182080ba0 (null) + 61016
6  libsqlite3.dylib               0x1820727dc sqlite3_step + 2708
7  libsqlite3.dylib               0x18203cc74 sqlite3_exec + 536
8  TestApp                   0x10478f8dc -[APMSqliteStore endTransaction] + 4333172956
9  TestApp                   0x10478f598 -[APMSqliteStore performTransaction:] + 4333172120
10 TestApp                   0x104767c58 -[APMMeasurement writeEventOnWorkerQueue:] + 4333010008
11 TestApp                   0x104767560 -[APMMeasurement handleEventOnWorkerQueue:] + 4333008224
12 TestApp                   0x10477b6d4 __51-[APMScheduler scheduleOnWorkerQueueBlockID:block:]_block_invoke + 4333090516
13 libdispatch.dylib              0x1815b2a54 _dispatch_call_block_and_release + 24
14 libdispatch.dylib              0x1815b2a14 _dispatch_client_callout + 16
15 libdispatch.dylib              0x1815f104c _dispatch_queue_serial_drain$VARIANT$armv81 + 520
16 libdispatch.dylib              0x1815f19bc _dispatch_queue_invoke$VARIANT$armv81 + 340
17 libdispatch.dylib              0x1815f23a8 _dispatch_root_queue_drain_deferred_wlh$VARIANT$armv81 + 384
18 libdispatch.dylib              0x1815fa4b0 _dispatch_workloop_worker_thread$VARIANT$armv81 + 640
19 libsystem_pthread.dylib        0x18185af1c _pthread_wqthread + 932
20 libsystem_pthread.dylib        0x18185ab6c start_wqthread + 4

#16. com.apple.NSURLConnectionLoader
0  libsystem_kernel.dylib         0x181727568 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1817273e0 mach_msg + 72
2  CoreFoundation                 0x181bde308 __CFRunLoopServiceMachPort + 196
3  CoreFoundation                 0x181bdbed4 __CFRunLoopRun + 1424
4  CoreFoundation                 0x181afbe58 CFRunLoopRunSpecific + 436
5  CFNetwork                      0x1823eb128 -[__CoreSchedulingSetRunnable runForever] + 780
6  Foundation                     0x1826330f4 __NSThread__start__ + 996
7  libsystem_pthread.dylib        0x18185c2b4 _pthread_body + 308
8  libsystem_pthread.dylib        0x18185c180 _pthread_body + 310
9  libsystem_pthread.dylib        0x18185ab74 thread_start + 4

#17. WebThread
0  libsystem_kernel.dylib              0x181727568 mach_msg_trap + 8
1  libsystem_kernel.dylib              0x1817273e0 mach_msg + 72
2  libdispatch.dylib                   0x1815e67c0 _dispatch_mach_send_and_wait_for_reply + 644
3  libdispatch.dylib                   0x1815e6c6c dispatch_mach_send_with_result_and_wait_for_reply$VARIANT$armv81 + 56
4  libxpc.dylib                        0x181897d7c xpc_connection_send_message_with_reply_sync + 196
5  libsystem_containermanager.dylib    0x1816d8f80 _send_sync_xpc_message + 52
6  libsystem_containermanager.dylib    0x1816d9334 _commonSystemContainerPathOperation + 204
7  CFNetwork                           0x1821bf590 systemGroupContainerURLWithGroupIdentifier(NSString*, NSString*) + 100
8  CFNetwork                           0x1821bf3e8 invocation function for block in getDafsa() + 36
9  libdispatch.dylib                   0x1815b2a14 _dispatch_client_callout + 16
10 libdispatch.dylib                   0x1815e5178 dispatch_once_f$VARIANT$armv81 + 60
11 CFNetwork                           0x1821bf3c0 lookupDomains(__CFString const*) + 448
12 CFNetwork                           0x1821c5d68 _CFHostIsDomainTopLevel + 12
13 WebKitLegacy                        0x18ae71664 WKIsPublicSuffix + 128
14 WebCore                             0x18a709650 WebCore::topPrivatelyControlledDomain(WTF::String const&) + 388
15 WebCore                             0x18a6b6750 WebCore::Page::mainFrameLoadStarted(WebCore::URL const&, WebCore::FrameLoadType) + 52
16 WebCore                             0x189ed8eb0 WebCore::FrameLoader::loadWithDocumentLoader(WebCore::DocumentLoader*, WebCore::FrameLoadType, WebCore::FormState*, WebCore::AllowNavigationToInvalidURL) + 336
17 WebCore                             0x189ed8c64 WebCore::FrameLoader::load(WebCore::FrameLoadRequest&&) + 580
18 WebKitLegacy                        0x18ad8e86c -[WebFrame loadRequest:] + 320
19 WebCore                             0x18ab46a08 HandleRunSource(void*) + 688
20 CoreFoundation                      0x181bde97c __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 24
21 CoreFoundation                      0x181bde8fc __CFRunLoopDoSource0 + 88
22 CoreFoundation                      0x181bde184 __CFRunLoopDoSources0 + 204
23 CoreFoundation                      0x181bdbd5c __CFRunLoopRun + 1048
24 CoreFoundation                      0x181afbe58 CFRunLoopRunSpecific + 436
25 WebCore                             0x189a092c8 RunWebThread(void*) + 560
26 libsystem_pthread.dylib             0x18185c2b4 _pthread_body + 308
27 libsystem_pthread.dylib             0x18185c180 _pthread_body + 310
28 libsystem_pthread.dylib             0x18185ab74 thread_start + 4

#18. AVAudioSession Notify Thread
0  libsystem_kernel.dylib         0x181727568 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1817273e0 mach_msg + 72
2  CoreFoundation                 0x181bde308 __CFRunLoopServiceMachPort + 196
3  CoreFoundation                 0x181bdbed4 __CFRunLoopRun + 1424
4  CoreFoundation                 0x181afbe58 CFRunLoopRunSpecific + 436
5  AVFAudio                       0x187461dc4 GenericRunLoopThread::Entry(void*) + 164
6  AVFAudio                       0x18748c830 CAPThread::Entry(CAPThread*) + 84
7  libsystem_pthread.dylib        0x18185c2b4 _pthread_body + 308
8  libsystem_pthread.dylib        0x18185c180 _pthread_body + 310
9  libsystem_pthread.dylib        0x18185ab74 thread_start + 4

**Comment by Kim-Deogwon** [comment]
@jangsy7883 안녕하세요. 전달해 주신 크래쉬 리포트는 잘 보았습니다. 다시 한번 AdFit SDK에 대한 관심 감사드립니다. 해당 자료는 AdFit 안정성 향상을 위한 참고 자료로 잘 활용하겠습니다.
