### ISSUE TITLE
Xcode 11 build issue

### ISSUE THREAD

**Issue by kor45cw** [adfit/adfit-ios-sdk#14]
Module compiled with Swift 5.0 cannot be imported by the Swift 5.1 compiler 

라고 하면서 모듈이 import 되지 않습니다. 확인부탁드립니다

**Comment by Kim-Deogwon** [comment]
Xcode 11 정식 출시 시점에 맞춰 대응 예정입니다.  
조금만 기다려 주시기 바랍니다. 관심 가져 주셔서 감사합니다.

**Comment by kor45cw** [comment]
@Kim-Deogwon 님 확인 감사합니다. 궁금한점이 있는데요 
대응 하신다면, 그 버전 이후부터는 항상 xcode 11 이상으로 빌드해야하는 것일까요?

**Comment by Kim-Deogwon** [comment]
@kor45cw 네. 스위프트의 ABI가 완벽하게 지원되기 전까지는 서로 짝이 맞아 가야만 할 것 같아요. 스위프트 5에서 ABI 많이 개선되었다고 해서 내심 기대했는데, 아직은 아닌가 봅니다.

**Comment by kor45cw** [comment]
@Kim-Deogwon 답변 감사합니다! 이슈는 close 하겠습니다~! (__)

**Comment by jangsy7883** [comment]
이번주에 iOS13의 배포가 예정되어있어서 대응을 준비 중입니다. 
AdFitSDK는 언제쯤 업데이트 될지 알 수 있을까요?

**Comment by Kim-Deogwon** [comment]
@jangsy7883 안녕하세요. 
네 9월19일에 iOS 13이 출시되는것으로 알고 있습니다. 
참고로 AdFitSDK의 공식 업데이트 시점은 xcode11의 정식 배포 시점에 맞춰 이뤄지고 있습니다. 
하지만 10.15 카탈리나 및 xcode11 업데이트 시점은 미정으로(공식사이트에서는 10월중으로만 표기) iOS13의 배포 시점과는 차이가 있습니다. 
xcode11이 정식으로 릴리즈 된 날로 부터 워킹 데이 기준으로 1~2일 내로 대응하기 위해 준비중에 있습니다.

**Comment by jangsy7883** [comment]
답변 감사합니다.
저희가 운영하는 서비스에서 iOS13대응에 중요한 부분이 있어서 빠르게 대응을 하려고 준비하고 있습니다. 
Xcode11 GM이 나오면서 앱스토어 업로드가 가능해져서 ADFitSDK만 업데이트 되길 기다리고 있습니다. ㅠㅠ
기다리고 있겠습니다.!

**Comment by kor45cw** [comment]
@Kim-Deogwon xcode 11.2 에서는 swift5.1.2 로 빌드되어야 하는것 같습니다. 확인부탁드립니다

**Comment by Kim-Deogwon** [comment]
@kor45cw 차주 월요일에 배포 예정입니다.

**Comment by Kim-Deogwon** [comment]
@kor45cw 3.0.9 버전 배포 하였습니다.

**Comment by kor45cw** [comment]
@Kim-Deogwon  감사합니다
