### ISSUE TITLE
Xcode 11 업데이트 후 컴파일 문제

### ISSUE THREAD

**Issue by appsstudioio** [adfit/adfit-ios-sdk#15]
Module compiled with Swift 5.0 cannot be imported by the Swift 5.1 compiler: /****/Pods/AdFitSDK/Frameworks/AdFitSDK.framework/Modules/AdFitSDK.swiftmodule/arm64.swiftmodule

위 오류가 발생하였습니다. 해당 문제를 해결하려면 별도의 프로젝트 설정이 필요한가요?

**Comment by jangsy7883** [comment]
Duplicate of #14

**Comment by jangsy7883** [comment]
#14
