### ISSUE TITLE
ios 13용 다크모드 적용 요청드립니다.

### ISSUE THREAD

**Issue by y2ducky** [adfit/adfit-ios-sdk#17]
iOS 13부터 다크모드가 제공됩니다.

앱에서 다크모드를 제공하더라도 AdFit의 텍스트 광고(띠배너)의 경우에는 배경이 흰색이라 사용자들이 눈이 부실 것으로 생각됩니다. 
앱 개발자가 배경과 글자의 색상을 직접 설정할 수 있는 API를 제공해주시거나, 다크모드 상태에 따라서 자동으로 변경되게 할 수 있는 방법을 제공주시면 좋겠습니다.

**Comment by Kim-Deogwon** [comment]
@y2ducky 
안녕하세요. 다크모드 제공에 따른 흰색 배경에서의 사용자들의 불편은 공감하는 바입니다. 사업적으로 여러 부서와의 커뮤니케이션 이슈가 있는 부분이어서 즉답 드리기 어려운점 이해 부탁드립니다. 개선 될 수 있도록 노력해보겠습니다.
