### ISSUE TITLE
iOS 13 modalPresentationStyle 이슈

### ISSUE THREAD

**Issue by appsstudioio** [adfit/adfit-ios-sdk#18]
안녕하세요. 광고 누르고 화면이 full screen으로 보이게 하고 싶은데
adFit에서 지원 되나요?
modalPresentationStyle = .fullscreen 옵션을 주고 싶은데 방법을 모르겠네요.

**Comment by Kim-Deogwon** [comment]
네 안녕하세요. 네, iOS13에서 광고 랜딩 이후 모달의 모습이 달라졌는데요. 현재 기능적으로 따로 API 제공되는 부분은 없구요. UI와 관련해서는 디자인과 협의중에 있습니다.

**Comment by Kim-Deogwon** [comment]
3.0.9 버전부터 랜딩브라우저의 modalPresentationStyle을 fullscreen으로 적용하였습니다.
