### ISSUE TITLE
XCode 11.3 이고 최신 sdk받았습니다.

### ISSUE THREAD

**Issue by kimdohak** [adfit/adfit-ios-sdk#19]
dyld: Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: /private/var/containers/Bundle/Application/1C434C30-E6EA-4DAC-B2FF-F44BA2791489/mhwlands-mobile.app/Frameworks/AdFitSDK.framework/AdFitSDK
  Reason: image not found

embedded에 추가하고 설명에 따라 했는데 컴파일은 완료되고 실행시 해당 에러가 나옵니다.

**Comment by Kim-Deogwon** [comment]
@kimdohak 혹시 오브젝티브 씨로 개발중인 프로젝트 일까요?

**Comment by kimdohak** [comment]
네 cocos2d를 사용중이지만 오브젝트C 입니다.

**Comment by Kim-Deogwon** [comment]
@kimdohak AdFit SDK는 Swift 기반으로 개발되었습니다. Objective-C 기반의 프로젝트에서 AdFit SDK를 사용하기 위해서는 Swift Standard 라이브러리들을 Embed 시켜주어야 합니다.
앱 프로젝트의 빌드 세팅에서 Always Embed Swift Standard Libraries 항목을 Yes로 설정해주세요.

**Comment by Kim-Deogwon** [comment]
해당 이슈로 부터 추가적인 코멘트 없이 오랜 시간 경과 하였기에 이 이슈는 클로즈 하겠습니다.
