### ISSUE TITLE
xcode 8.3 에서 빌드한 앱을 스토어 등록 시 경고 문구

### ISSUE THREAD

**Issue by venice81** [adfit/adfit-ios-sdk#2]
xcode 8.3에서 빌드된 앱을 스토어에 업로드 한 후 아래 내용이 포함된 메일을 받았습니다.

Missing Info.plist key - This app attempts to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSCalendarsUsageDescription key with a string value explaining to the user how the app uses this data.

EventKit, EventKitUI 프레임웍을 사용 시 캘린더에 접근하려는 이유를 설명해야 하는데 AdFit에서 이 프레임웍을 사용하는 이유는 무엇인가요?

**Comment by harange** [comment]
@venice81 
EventKit, EventKitUI Framework를 사용한 이유는 리치 미디어 광고 중 특정 일을 사용자 캘린더에 등록시키는 엑션을 대응하기 위해서 사용되었습니다.
