### ISSUE TITLE
framework 내 UIWebView 을 사용하나요?

### ISSUE THREAD

**Issue by storyhe** [adfit/adfit-ios-sdk#20]
안녕하세요?

앱 업로드 이후, AppStoreConnect 에서 메일이 옵니다.

```
We identified one or more issues with a recent delivery for your app, *****
 Your delivery was successful, but you may wish to correct the following issues in your next delivery:

ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs starting from December 2020 . See https://developer.apple.com/documentation/uikit/uiwebview for more information.
```

이 오고있습니다, 

내부 프로젝트에서는 uiwebview 쓰는게 없는데 grep 으로 찾아보니 `Binary file Frameworks/AdFitSDK.framework/AdFitSDK matches` 으로 나와서 문의 드립니다.

**Comment by Kim-Deogwon** [comment]
네 안녕하세요. 넵 해당 부분에 대해서 정확한 업데이트 일정이 픽스된 것은 아니지만 연내에 iOS 최소 지원버전을 상향 시키면서 해당 api에 대해 제거할 예정입니다. 관련 부분은 작은 범위이지만, 최소 지원버전 상향을 위해서는 고려할 사항이 많아 업데이트가 더뎌질 수 있는 부분은 양해 부탁드리겠습니다. 감사합니다.

**Comment by Kim-Deogwon** [comment]
@storyhe 안녕하세요. 해당 부분에 대해 수정하여 3.0.11 버전으로 배포 하였습니다. 기다려 주셔서 감사합니다.

**Comment by Kim-Deogwon** [comment]
해당 이슈는 3.0.11 버전에서 수정되었으므로 이 이슈는 클로즈 합니다.

**Comment by Kim-Deogwon** [comment]
해당 이슈는 3.0.11 버전에서 수정되었으므로 이 이슈는 클로즈 합니다.
