### ISSUE TITLE
Missing required module 'FrameworkPrivate'

### ISSUE THREAD

**Issue by appsstudioio** [adfit/adfit-ios-sdk#21]
SDK 3.4.0으로 업데이트이후 "Missing required module 'FrameworkPrivate'" 에러 뜨면서
빌드가 안되고 있는데 프로젝트 설정을 어떻게 해주어야 하나요?
Xcode 11.5를 사용하고 있습니다. 
샘플 프로젝트 열어서 빌드해도 동일한 현상 입니다.

**Comment by Kim-Deogwon** [comment]
@appsstudioio  넵 현재 확인 중에 있습니다.

**Comment by Kim-Deogwon** [comment]
@appsstudioio 안녕하세요. 관련 이슈 수정하여 3.4.1 버전으로 배포 하였습니다. 감사합니다.

**Comment by kor45cw** [comment]
@Kim-Deogwon 수정된 버전으로 빌드하였더니 크래시 발생하는것 같습니다. 확인부탁드려요~

**Comment by kor45cw** [comment]
기기는 iOS 13.5.1  iPhone 11 Pro Max 실기기 debug 빌드였습니다

**Comment by Kim-Deogwon** [comment]
@kor45cw 제가 가진 환경에서는 재현이 안되는것 같아, 크래쉬 로그 또는 재현경로 같은 것들이 있다면 도움을 드릴 수 있을것 같습니다.

**Comment by kor45cw** [comment]
@Kim-Deogwon 

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Attempt to insert non-property list object {
    ads =     (
                {
            clientId = "발급받은 id";
            size = "<null>";
            type = banner;
        }
    );
} for key AdFitStore'

이렇게 에러 발생합니다.

**Comment by Kim-Deogwon** [comment]
@kor45cw 이슈 내용 확인 했습니다. 빠른 시일 내에 대응하여 재배포 할 수 있도록 하겠습니다.

**Comment by Kim-Deogwon** [comment]
@kor45cw 해당 이슈 수정하여 3.4.2 버전으로 배포 하였습니다. 감사합니다.

**Comment by kor45cw** [comment]
확인하였습니다 감사합니다

**Comment by Kim-Deogwon** [comment]
더 이상 이슈는 없는것 같아 클로징 합니다.
