### ISSUE TITLE
Error 3.4.0

### ISSUE THREAD

**Issue by kor45cw** [adfit/adfit-ios-sdk#22]
3.4.0으로 업데이트 한 후에 
Missing required module 'FrameworkPrivate'
에러 발생하고 있습니다 확인부탁드려요~!

**Comment by kor45cw** [comment]
아래쪽에 같은 이슈가 있어 duplicate로 close 합니다 #21

**Comment by Kim-Deogwon** [comment]
@kor45cw  안녕하세요. 관련 이슈 수정하여 3.4.1 버전으로 배포 하였습니다. 감사합니다.
