### ISSUE TITLE
iOS 14 AppTrackingTransparency 권한 문의

### ISSUE THREAD

**Issue by jinsnet** [adfit/adfit-ios-sdk#23]
안녕하세요. 

애플에서 ios14부터 IDFA 를 얻기 위해서는 앱 권한을 획득해야한다는 소식을 받았습니다. 

https://developer.apple.com/documentation/apptrackingtransparency

https://support.google.com/admob/answer/9997589?visit_id=637334752342640009-977989216&rd=1

애드핏은 IDFA이 없어도 광고 출력에 문제가 없는지 문의 드립니다. 

감사합니다.

**Comment by kyungw00k** [comment]
@Kim-Deogwon 이 이슈 확인 부탁드립니다!

**Comment by Kim-Deogwon** [comment]
@jinsnet 
안녕하세요. 
먼저 간단하게 답변을 드리자면 IDFA 값이 없어도 광고 출력 에는 문제가 없습니다. 
다만, IDFA 값이 있다면 매출에 도움이 될 수는 있습니다. 
관련하여 iOS14에서 IDFA 트래킹 권한 획득을 위한 절차는 AdFit을 통해 가이드 될 수 있도록 하겠습니다. 
감사합니다.

**Comment by jinsnet** [comment]
빠른 답변 감사합니다. 일단 광고 출력에 문제 없으니 다행이네요.
