### ISSUE TITLE
[!] Unable to read the license file `LICENSE.txt` for the spec `AdFitSDK (3.5.3)`

### ISSUE THREAD

**Issue by bhbfhfb** [adfit/adfit-ios-sdk#24]
Pod을 이용하여 설치시 이런 메시지가 나옵니다.

[!] Unable to read the license file `LICENSE.txt` for the spec `AdFitSDK (3.5.3)`

기능 동작에 문제는 없습니다.

**Comment by Kim-Deogwon** [comment]
@bhbfhfb 안녕하세요. 확인 감사합니다. 
3.4.0 배포부터 LICENSE.txt 를 LICENSE.md로 배포 하고 있었네요. 다음 배포에는 다시 LICENSE.txt로 배포 될 수 있도록 하겠습니다. 
AdFitSDK에 대한 관심 감사합니다.
