### ISSUE TITLE
WARN : Vital_KSCrashSentry.c (102): Vital_KSCrashType 

### ISSUE THREAD

**Issue by hajini** [adfit/adfit-ios-sdk#26]
가이드대로 했는데, 아래와 같은 메시지가 나오고 광고도 뜨질 않네요. 
확인 가능하실까요?

WARN : Vital_KSCrashSentry.c (102): Vital_KSCrashType vital_kscrashsentry_installWithContext(Vital_KSCrash_SentryContext *, Vital_KSCrashType, void (*)(void *)): KSCrash: App is running in a debugger. Crash handling is enabled via configuration.

INFO : Vital_KSCrashSentry.c (105): Vital_KSCrashType vital_kscrashsentry_installWithContext(Vital_KSCrash_SentryContext *, Vital_KSCrashType, void (*)(void *)): Installing handlers with context 0x104645d88, crash types 0x2f.

WARN : Vital_KSCrashSentry_MachException.c (340): _Bool vital_kscrashsentry_installMachHandler(Vital_KSCrash_SentryContext *const): Process is being debugged. Not installing handler.

**Comment by nairs77** [comment]
@hajini 안녕하세요. 확인 감사합니다.
우선 노출된 로그는 내부적인 로직을 체크하기 위한 로그이며, 오류는 아닙니다. 그리고 광고의 송출 및 노출과는 크게 연관이 없는 부분입니다. 
광고가 나오지 않는 부분은 adfit 가이드를 다시 한번 참조 부탁 드립니다. (https://adfit.github.io)
