### ISSUE TITLE
Xcode 12.2 업데이트 후 빌드 

### ISSUE THREAD

**Issue by jangsy7883** [adfit/adfit-ios-sdk#27]
Xcode가 업데이트 되면서 Swift의 버전도 5.3.1로 업데이트 되었습니다. 
그러면서 기존 AdFitSDK가 빌드가 안되는 현상이 발생합니다..

`Module compiled with Swift 5.3 cannot be imported by the Swift 5.3.1 compiler`

확인 부탁드립니다.

그런데 이 문제를 근본적으로 해결할 방법이 없을까요? Swift의 버전이 올라갈때마다 이 현상을 경험하고 있는데, 근본적으로 이 문제를 해결할 방법을 찾아보는 것도 좋을 것 같습니다.

저도 잘 알지는 못하짐만 `BUILD_LIBRARY_FOR_DISTRIBUTION ` 옵션과 관련이 있을 것 같은데, 아래 링크를 한번 봐주시면 좋을 것 같습니다.

http://minsone.github.io/ios/mac/ios-wwdc-2019-binary-frameworks-in-swift-little-summary-and-translate

**Comment by Kim-Deogwon** [comment]
@jangsy7883 AdFit 3.6.2 버전 배포 하였습니다. 관심 감사드리며, 제안 주신 옵션 내부 검토 후 반영 하도록 하겠습니다.

**Comment by hajini** [comment]
3.6.2 버전은 pod install 로는 설치할 수 가 없는 상태인가요? 
pod 'AdFitSDK' 로 설치하니 3.5.3 버전이 설치되네요.

**Comment by Kim-Deogwon** [comment]
@hajini  podfile에서 AdFitSDK 버전을 3.6.2 로 바꾸신 후, 'pod install --repo-update' 해보시겠어요? 
3.6.2 버전도 pod을 통해 설치 할 수 있도록 지원하고 있습니다.

**Comment by hajini** [comment]
@Kim-Deogwon 문제 없이 업데이트 되었습니다. 빠른 답변 감사드립니다.
