### ISSUE TITLE
ios14 이후 빌드

### ISSUE THREAD

**Issue by leesungju** [adfit/adfit-ios-sdk#28]
라이브러리 받아서 쓰고 있는데  archive 시 해당 에러가 납니다
The linked and embedded framework 'AdFitSDK.framework' is missing one or more architectures required by this target: armv7.

**Comment by Kim-Deogwon** [comment]
@leesungju 안녕하세요. 디바이스 및 앱 최소지원 OS를 알 수 있을까요? 참고로 AdFit 최신버전의 최소지원 OS는 iOS11 입니다.

**Comment by leesungju** [comment]
버전을 올렸더니 잘되네요 ios8 이상 지원하고 있었습니다.
빠른대응 감사합니다.
