### ISSUE TITLE
Issue : ATTrackingManager.requestTrackingAuthorization

### ISSUE THREAD

**Issue by hajini** [adfit/adfit-ios-sdk#29]
안녕하세요. 
SDK 3.7.0 버전 업데이트 후, 애플 정책에 따라 ATTrackingManager.requestTrackingAuthorization 를 추가하였는데, 
빌드는 문제없이 됩니다만, iOS 버전 확인할때 에러가 발생하네요

로그창에는 아래와 같이 뜨고
CoreSimulator 732.18.0.2 - Device: iPhone 12 (AD551745-8F30-49FD-9155-2F56448F99E4) - Runtime: iOS 14.2 (18B79) - DeviceType: iPhone 12
(lldb) 

에러 발생하는 위치 창에는 Thread 4 : signal SIGABRT 발생합니다. 
libsystem_kernel.dylib`__abort_with_payload:
    0x7fff5e722788 <+0>:  movl   $0x2000209, %eax          ; imm = 0x2000209 
    0x7fff5e72278d <+5>:  movq   %rcx, %r10
    0x7fff5e722790 <+8>:  syscall 
->  0x7fff5e722792 <+10>: jae    0x7fff5e72279c            ; <+20>      -
    0x7fff5e722794 <+12>: movq   %rax, %rdi
    0x7fff5e722797 <+15>: jmp    0x7fff5e7016a1            ; cerror_nocancel
    0x7fff5e72279c <+20>: retq   
    0x7fff5e72279d <+21>: nop    
    0x7fff5e72279e <+22>: nop    
    0x7fff5e72279f <+23>: nop    

아래에 코드 첨부 드립니다. 

        let bannerAdView = AdFitBannerAdView(clientId: "DAN-t84lawxurwvt", adUnitSize: "320x50")
        bannerAdView.rootViewController = self
        bannerAdView.delegate = self
        bannerAdView.frame = CGRect(x: 0, y: 0, width: adViewBanner.frame.size.width, height: 50)
        bannerAdView.autoresizingMask = [.flexibleWidth, .flexibleTopMargin]
        adViewBanner.addSubview(bannerAdView)
        
        if #available(iOS 14, *) {
            ATTrackingManager.requestTrackingAuthorization { (status) in
               // 프린트 찍어 보니 여기서 에러 발생하네요.

                switch status {
                case .authorized:
                    return bannerAdView.loadAd()
                case .denied:
                    return bannerAdView.loadAd()
                case .notDetermined:
                    return bannerAdView.loadAd()
                case .restricted:
                    return bannerAdView.loadAd()
                default:
                    return bannerAdView.loadAd()
                }
            }
        } else {
            bannerAdView.loadAd()
        }

Xcode ver 12.2 이며, 아이폰12 시뮬레이터로 돌렸습니다. 아이폰 11 및 다른 시뮬레이터 돌려도 마찬가지입니다.

**Comment by hajini** [comment]
올리자마자 보니 코드를 영 잘못 짜놨네요;;; status 지정을 안해놨군요. Close 부탁드립니다.

**Comment by nairs77** [comment]
혹시 plist에 Privacy - Tracking Usage Description 설정은 하셨나요?
아래 링크 참조 하시길 바랍니다.

https://github.com/adfit/adfit-ios-sdk/wiki/%EC%8B%9C%EC%9E%91%ED%95%98%EA%B8%B0#3-attapp-tracking-transparency-framework-%EC%A0%81%EC%9A%A9

**Comment by hajini** [comment]
네 info.plist 수정 해놨는데 그러네요

**Comment by nairs77** [comment]
@hajini 전달해 주신, 에러는 info.plist에 해당 키처리가 되지 않아서 발생한 현상 같습니다. info.plist에 해당 키를 제거 후, 테스트 해보니 전달해 주신 동일한 에러가 발생하고 있는 것으로 보입니다.

**Comment by hajini** [comment]
@nairs77 답변 감사드립니다. 다시 한번 돌려봐야겠네요.
