### ISSUE TITLE
AdFit SDK 에서 크래시 문제

### ISSUE THREAD

**Issue by venice81** [adfit/adfit-ios-sdk#3]
AdFit 라이브러리에서 크래시 되는 문제가 있어 로그를 남깁니다.

확인 후 수정되었으면 좋겠네요~

크래시는 아래 3종류 입니다.
------------------------------------------------------------------
Crashed: com.apple.main-thread
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x00000000f1475049

Crashed: com.apple.main-thread
0  libobjc.A.dylib                0x1ae54dc6 objc_msgSend + 5
1  MY_APPLICATION                 0x6ca8bf +[AdamDelegateManager fireDelegateDidFailToReceiveAd:error:] (AdamDelegateManager.m:86)
2  MY_APPLICATION                 0x6b7f03 -[AdamAdView didFinishGetAdModel:error:] (AdamAdView.m:496)
3  Foundation                     0x1c4f202f __NSFireDelayedPerform + 458
4  CoreFoundation                 0x1bb7c637 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 14
5  CoreFoundation                 0x1bb7c339 __CFRunLoopDoTimer + 832
6  CoreFoundation                 0x1bb7bd37 __CFRunLoopDoTimers + 188
7  CoreFoundation                 0x1bb79dd5 __CFRunLoopRun + 780
8  CoreFoundation                 0x1bacd0ef CFRunLoopRunSpecific + 470
9  CoreFoundation                 0x1baccf11 CFRunLoopRunInMode + 104
10 GraphicsServices               0x1d277b41 GSEventRunModal + 80
11 UIKit                          0x20e51e83 UIApplicationMain + 150
12 MY_APPLICATION                 0x149d3f main (main.m:16)
13 libdyld.dylib                  0x1b2ba4eb start + 2

------------------------------------------------------------------
Crashed: com.apple.main-thread
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000000

Crashed: com.apple.main-thread
0  libobjc.A.dylib                0x1c6b26b4 lookUpImpOrForward + 59
1  libcoretls_cfhelpers.dylib     0xffffffbf (Missing)
2  libobjc.A.dylib                0x1c6b2675 _class_lookupMethodAndLoadCache3 + 26
3  libobjc.A.dylib                0x1c6b88cf _objc_msgSend_uncached + 14
4  MY_APPLICATION                 0x620723 +[AdamDelegateManager fireDelegateDidReceiveAd:] (AdamDelegateManager.m:63)
5  MY_APPLICATION                 0x60e103 __40-[AdamAdView didFinishGetAdModel:error:]_block_invoke.179 (AdamAdView.m:452)
6  libdispatch.dylib              0x1caee083 _dispatch_client_callout + 22
7  libdispatch.dylib              0x1caf9b33 _dispatch_continuation_pop + 500
8  libdispatch.dylib              0x1cb04a7d _dispatch_source_latch_and_call + 166
9  libdispatch.dylib              0x1caefcb5 _dispatch_source_invoke + 798
10 libdispatch.dylib              0x1caf2477 _dispatch_main_queue_callback_4CF + 500
11 CoreFoundation                 0x1d4044a7 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 8
12 CoreFoundation                 0x1d40278f __CFRunLoopRun + 1422
13 CoreFoundation                 0x1d351533 CFRunLoopRunSpecific + 486
14 CoreFoundation                 0x1d351341 CFRunLoopRunInMode + 104
15 GraphicsServices               0x1eb28bfd GSEventRunModal + 156
16 UIKit                          0x2255fe67 -[UIApplication _run] + 574
17 UIKit                          0x2255a591 UIApplicationMain + 150
18 MY_APPLICATION                 0x9fd3f main (main.m:16)
19 libdispatch.dylib              0x1cb1b50b (Missing)

-------------------------------------------
Fatal Exception: NSRangeException
*** -[__NSArrayM objectAtIndex:]: index 1 beyond bounds [0 .. 0]

Fatal Exception: NSRangeException
0  CoreFoundation                 0x1b9fbb3d __exceptionPreprocess
1  libobjc.A.dylib                0x1ac83067 objc_exception_throw
2  CoreFoundation                 0x1b90b8cb -[__NSArrayM objectAtIndex:]
3  MY_APPLICATION                      0x7a6f4f ADNStringFromNetworkReachabilityStatus
4  MY_APPLICATION                      0x7912a7 ALSHA1Digest
5  MY_APPLICATION                      0x1cbcf9 -[ALAdapterAdam didReceiveAd:] (ALAdapterAdam.m:112)
6  MY_APPLICATION                      0x65a103 __40-[AdamAdView didFinishGetAdModel:error:]_block_invoke.179 (AdamAdView.m:452)
7  libdispatch.dylib              0x1b0c9783 _dispatch_client_callout
8  libdispatch.dylib              0x1b0d5155 _dispatch_continuation_pop
9  libdispatch.dylib              0x1b0e014d _dispatch_source_latch_and_call
10 libdispatch.dylib              0x1b0cb285 _dispatch_source_invoke
11 libdispatch.dylib              0x1b0cdbd3 _dispatch_main_queue_callback_4CF
12 CoreFoundation                 0x1b9b7d69 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
13 CoreFoundation                 0x1b9b5e19 __CFRunLoopRun
14 CoreFoundation                 0x1b9090ef CFRunLoopRunSpecific
15 CoreFoundation                 0x1b908f11 CFRunLoopRunInMode
16 GraphicsServices               0x1d0b3b41 GSEventRunModal
17 UIKit                          0x20c8de83 UIApplicationMain
18 MY_APPLICATION                      0xebd3f main (main.m:16)
19 libdyld.dylib                  0x1b0f64eb start

**Comment by astrokil** [comment]
@venice81  안녕하세요.

올려주신 로그를 통해 파악하기로는, AdamAdView 객체의 delegate 프로퍼티에 할당된 객체가 메모리 상에서 해제된 것으로 보입니다.
delegate 프로퍼티가 assign 속성이기 때문에, 대상 객체가 해제될 때에 nil 또는 다른 객체로 직접 할당해 주어야 합니다.
(또는 대상 객체가 해제되지 않도록 관리해 주어야 합니다)
추후 업데이트 시 해당 프로퍼티는 weak 속성으로 변경하도록 하겠습니다.

세번째 로그는 애드립 SDK와 관련된 이슈 같은데요, delegate 객체 해제와 관련된 부분인지는 파악이 어렵습니다.
일단 상기한 바와 같이 처리하신 후, 동일 증상이 반복되면 애드립에 문의를 해주시는 것이 좋을 것 같습니다.

감사합니다.
