### ISSUE TITLE
앱스토어 업로드시 오류가 발행합니다.

### ISSUE THREAD

**Issue by asrada2001** [adfit/adfit-ios-sdk#30]
아카이브를 앱스토어에 업로드 할 때 다음과 같은 오류가 발생하는데 원인이 무엇일까요?

> No suitable application records were found. Verify your bundle identifier ‘com.kakao.biz.AdFitSDK’ is correct.

**Comment by nairs77** [comment]
@asrada2001 

문의하신 사항에 대해서는 처음 전달 받는 이슈라 정확한 이유를 아직 파악을 못했습니다.
App Store Connect에 등록된 정보에 이상이 없다면, 아래의 링크의 경우에 대해서 확인 부탁 드립니다.

https://github.com/Alamofire/Alamofire/issues/2020

해당 링크에 특정 사용자는 Cocoapod을 재설치 한 것으로 되어 있는데 한번 확인 부탁 드립니다.
