### ISSUE TITLE
AdFitSDK Crash (UIApplication AdFitSDK isBackground) 관련 문의

### ISSUE THREAD

**Issue by MarkusOhADOP** [adfit/adfit-ios-sdk#32]
iOS AdFitSDK Banner를 사용 중입니다. 기술 이슈가 발생해 문의 드립니다.
SDK 버전은 3.7.0으로 다음과 같은 에러가 하루 약 300건 정도로 지속적으로 발생중입니다. Firebase Crashlytics에선 다음과 같은 크래시 로그가 수집되었습니다.

이 에러가 어떤 경우에 일어나는 지, 또 이 Crash 이슈 솔루션에 대해 가이드 부탁드립니다.

· $sSo13UIApplicationC8AdFitSDKE12isBackgroundSbvgZTf4d_n + 292
· $s8AdFitSDK15ViewableCheckerC05checkD10Impression33_01DB66B915F199ED3A35A2024F81342CLL4area8interval18isAllowCoverdLayer17allowedCoverAlpha7handler17continueConditionySd_SdSb12CoreGraphics7CGFloatVyAC11CheckResultVSg_s5Error_pSgtcSbyctFyycfU_ + 208

Crash Stack을 드리자면, 다음과 같습니다:

viewableChecker.viewableImpression.workingQueue 
0 libsystem_kernel.dylib 0x1c624ef5c __ulock_wait + 8 
1 libdispatch.dylib 0x197eee794 _dlock_wait + 56 
2 libdispatch.dylib 0x197eee528 _dispatch_thread_event_wait_slow + 56 
3 libdispatch.dylib 0x197efc708 __DISPATCH_WAIT_FOR_QUEUE__ + 352 
4 libdispatch.dylib 0x197efc2b0 _dispatch_sync_f_slow + 148 
5 libswiftDispatch.dylib 0x1ade660e4 implicit closure #2 in implicit closure #1 in OS_dispatch_queue.sync<A>(execute:) + 180 
6 libswiftDispatch.dylib 0x1ade66798 partial apply for implicit closure #2 in implicit closure #1 in OS_dispatch_queue.sync<A>(execute:) + 56 
7 libswiftDispatch.dylib 0x1ade654a0 OS_dispatch_queue._syncHelper<A>(fn:execute:rescue:) + 360 
8 libswiftDispatch.dylib 0x1ade65c6c OS_dispatch_queue.sync<A>(execute:) + 168 
9 AdFitSDK 0x105def00c $sSo13UIApplicationC8AdFitSDKE12isBackgroundSbvgZTf4d_n + 292 
10 AdFitSDK 0x105e3aa1c $s8AdFitSDK15ViewableCheckerC05checkD10Impression33_01DB66B915F199ED3A35A2024F81342CLL4area8interval18isAllowCoverdLayer17allowedCoverAlpha7handler17continueConditionySd_SdSb12CoreGraphics7CGFloatVyAC11CheckResultVSg_s5Error_pSgtcSbyctFyycfU_ + 208 
11 AdFitSDK 0x105dfc3f0 $sIeg_IeyB_TR + 20 
12 libdispatch.dylib 0x197eeddb0 _dispatch_client_callout + 20 
13 libdispatch.dylib 0x197ef112c _dispatch_continuation_pop + 416 
14 libdispatch.dylib 0x197f02c08 _dispatch_source_invoke + 1260 
15 libdispatch.dylib 0x197ef4fd8 _dispatch_lane_serial_drain + 272 
16 libdispatch.dylib 0x197ef5c5c _dispatch_lane_invoke + 408 
17 libdispatch.dylib 0x197effd78 _dispatch_workloop_worker_thread + 708 
18 libsystem_pthread.dylib 0x1e3da9814 _pthread_wqthread + 276 
19 libsystem_pthread.dylib 0x1e3db076c start_wqthread + 8

감사합니다.

**Comment by Kim-Deogwon** [comment]
@MarkusOhADOP  안녕하세요. 해당 문의와 관련하여, 해당 크래쉬가 재현되는 샘플 또는 해당 SDK가 들어가는 앱 등을 알려주시면 이슈 해결에 도움이 될 수 있을것 같습니다.
