### ISSUE TITLE
HTTP 400 에러가 계속뜹니다.

### ISSUE THREAD

**Issue by jenthous** [adfit/adfit-ios-sdk#33]
xcode 13 이고. ios14, 15에서도 동일한 증상이 나타납니다.

xcode에서 빌드하면 정상적인 노출이 되나,

아카이브한 뒤 distribute 후 test flight 로 테스트할때 400에러가 뜹니다.

`[error localizedDescription]` 는 `HTTP failed. status: 400` 입니다.

**Comment by HuanSuh** [comment]
@jenthous 혹시 해결 방법 찾으셨나요??

**Comment by jenthous** [comment]
@HuanSuh 아뇨 ㅜㅜ
3.7.0에서도 같은 증상입니다
애드핏 sdk가 xcode13 이랑 안맞나봐요

**Comment by HuanSuh** [comment]
@jenthous 혹시 이전 버전의 xcode에서는 정상적으로 동작했었나요??
이것저것 방법을 시도해보고 있는데 안되네요ㅜ 혹시나 방법 찾으시면 공유 부탁드릴게요ㅜ

**Comment by jenthous** [comment]
@HuanSuh xcode12에서도 안되시나요?
12에서는 잘됐었는데 자동으로 13업데이트 되버려서...
12에서 테스트를 아직안해봤네요

**Comment by HuanSuh** [comment]
@jenthous 저도 xcode13, SDK3.8.5, ios14에서 확인해보았습니다.
xcode downgrade이후 테스트 해봐야겠네요. 감사합니다.

**Comment by jenthous** [comment]
@HuanSuh xcode 12에서 되시면 피드백부탁드려요! 
감사합니다.

**Comment by nairs77** [comment]
@jenthous @HuanSuh 
대응이 늦어서 죄송합니다.
해당 이슈는 xcode13에서 제기된 이슈로, 문제는 다음과 같습니다.

* 원인 : xcode 13에서 App Store Connect에 업로드시에 버전에 대한 오류를 잡아주는 기능이 추가되면서, 앱내 번들의 정보도 앱의 버전과 동일시 되는 오류가 있는 것 같습니다. AdFit SDK도 내부 번들에 명시된 Version을 통한 관리가 이루어지는데, xcode 13으로 배포시 AdFit SDK 버전이 앱의 버전으로 동기화 되면서 유효하지 않은 버전으로 인식되어 발생된 문제로 판단됩니다.
(관련 근거 : [xcode13 Release Note](https://developer.apple.com/documentation/xcode-release-notes/xcode-13-release-notes))
`When uploading an app to App Store Connect, the distribution assistant in Xcode detects whether your app has a valid build number (CFBundleVersion). If your app has an invalid number (like one that was used previously, or precedes your current build number), the distribution assistant provides an option to automatically increment it to a valid number. In addition, the distribution assistant ensures that the build numbers of all embedded content in your app (such as app extensions, App Clips, or watchOS apps) are in sync with your app. Note that this doesn’t modify your source code or your archive; Xcode updates the build number in a staged copy of your app before packaging and uploading it to App Store Connect. (59826409)`

* 대책 : 긴급 재배포 하도록 하겠습니다.  (배포 예정 : 2021년 10월 6일 ASAP)

**Comment by HuanSuh** [comment]
@nairs77  대응 감사합니다 :) 좋은 하루 되세요~

**Comment by jenthous** [comment]
@nairs77 감사합니다. 해결됐습니다.
