### ISSUE TITLE
iOS15에서 배너 터치시 뜨는 팝업 상단바가 검은색으로 나옵니다.

### ISSUE THREAD

**Issue by JeongminLee-Tnear** [adfit/adfit-ios-sdk#34]
상단바가 흰색이 아닌 투명화된 검은색으로 나와서 제목이나 엑스, 공유 버튼이 안보입니다. 
navigationBar 색상에 영향이 간것같은데, 하얗게 수정 부탁드립니다.

**Comment by Kim-Deogwon** [comment]
@JeongminLee-Tnear @y2ducky 안녕하세요. 해당 현상 확인되었고, 빠른 시일내에 배포 할 수 있도록 하겠습니다. 감사합니다!!

**Comment by Kim-Deogwon** [comment]
@JeongminLee-Tnear @y2ducky 안녕하세요. 3.11.5 로 배포 하였습니다. 많은 관심 감사드립니다.
