### ISSUE TITLE
xcdoe 12.5.1(12E507) 빌드시 스위프트 버전오류가 있습니다. 해결방법이 있을까요?

### ISSUE THREAD

**Issue by HaeSeongPark** [adfit/adfit-ios-sdk#35]
Failed to build module 'AdFitSDK' from its module interface; the compiler that produced it, 'Apple Swift version 5.3.1 (swiftlang-1200.0.41 clang-1200.0.32.8)', may have used features that aren't supported by this compiler, 'Apple Swift version 5.4.2 (swiftlang-1205.0.28.2 clang-1205.0.19.57)'

사용 환경
m1 mac ( Big sur 11.4 )
AdFitSDk 3.7.0
xcdoe 12.5.1
target version 12.0

**Comment by Kim-Deogwon** [comment]
@HaeSeongPark 

안녕하세요. 

3.7.0 버전을 사용하시는 군요. 사용하시는 XCode버전을 낮추시던지, 사용하시는 AdFit SDK의 버전을 올리신다면 해결 될 것 같습니다. 

감사합니다.
