### ISSUE TITLE
AdFitSdk VSCode에서 빌드 시 오류

### ISSUE THREAD

**Issue by super1947** [adfit/adfit-ios-sdk#37]
module compiled with Swift 5.4 cannot be imported by the Swift 5.5.1 compiler: myprojectfolder/ios/Pods/AdFitSDK/Frameworks/AdFitSDK.framework/Modules/AdFitSDK.swiftmodule/arm64.swiftmodule
flutter ios simulator로 빌드 시 이런 메시지가 뜨면서 빌드가 안되는 문제가 있는데 어떤 이슈일까요?

AdFitSdk 버전 : 3.11.5
Xcode 버전 : 13
Swift 버전 : 5.5.1

**Comment by Kim-Deogwon** [comment]
@super1947 

안녕하세요. 

혹시 VSCode에서 빌드라고 하시면 XCode가 아니라 VSCode를 사용하여 빌드 하신 다는 말씀이실까요?
