### ISSUE TITLE
Xcode 13.2.1 (13C100) 빌드 시, swift version 관련 경고 발생

### ISSUE THREAD

**Issue by NohEunTae** [adfit/adfit-ios-sdk#38]
Xcode 13.2.1 (13C100) 빌드 시, 아래와 같은 warning이 발생하여 문의드립니다.
그냥 진행해도 문제가 없을지, 아니면 해결 방안이 있다면 대안에 대한 가이드 부탁드립니다.

***'프로젝트경로/Pods/AdFitSDK/Frameworks/AdFitSDK.framework/Modules/AdFitSDK.swiftmodule/Project/x86_64-apple-ios-simulator.swiftsourceinfo' is either malformed or generated by a different Swift version. Note that it uses an unstable format and may leak internal project details, it should not be distributed alongside modules***

사용 환경
intel mac ( Big sur 11.6.1 )
AdFitSDK 3.11.5
Xcode 13.2.1
iOS Deployment Target 12.0

**Comment by Kim-Deogwon** [comment]
@NohEunTae 

안녕하세요. 

XCODE 13 이후 버전 부터 다른 버전의 스위프트 컴파일러로 빌드된 프레임워크를 임포트시 경고가 표시되고 있고, 이는 프레임워크 내부의 .swiftsourceinfo 파일의 존재로 인해 발생하는것으로 확인 되었습니다. 
 
SDK 동작에는 지장이 없으며, 현재 버전으로 개발 하셔도 될 것 같습니다. 

추후 차기 배포에는 신규 배포된 스위프트 컴파일러 버전으로 배포 혹은, 빌드시 .swiftsourceinfo 파일이 포함되지 않도록 빌드 하여 전달할 예정입니다. 

해당 이슈와 관련하여 히스토리는 다음과 같습니다.  

XCODE의 스위프트 버전이 업데이트 될때 이전 버전의 스위프트 버전으로 컴파일된 프레임워크를 지원하지 않아, 매번 새로운 XCODE가 나올때마다 빌드를 새로 전달해야 하는 불편함이 있었습니다. 
그래서 "BUILD_LIBRARY_FOR_DISTRIBUTION=YES" 설정을 통해 컴파일러 환경정보를 전달하여 하위 하위 버전의 스위프트 컴파일러로 빌드된 프레임워크를 지원 하였습니다. 
이 과정에서 프레임워크 내부 /Modules/AdFiSDK.swiftmodule/Project/*.swiftsourceinfo 파일이 생성되고 이 파일들로 인하여, 경고를 표시 하게 되었습니다.

**Comment by Kim-Deogwon** [comment]
@NohEunTae 

안녕하세요. 

3.11.5 의 레포지토리를 다시 받아 보시겠어요?

해당 팟은 이미 받아서 아마 캐쉬에 남아 있을텐데요.   아래와 같은 명령어로 캐쉬 클린 후 다시 받아 보셔요. 

"pod cache clean 'AdFit' --all" 

그럼 "AdFitSDK.framework/Modules/AdFitSDK.swiftmodule/Project" 폴더가 제거 되면서 .swiftsourceinfo 파일도 같이 제거 되어 더이상 warning 문구가 나오지 않을겁니다. 

감사합니다.
