### ISSUE TITLE
AdFitSDK 3.12.6 이상 "Reference to 'SDAnimatedImageProvider' is ambiguous' 오류

### ISSUE THREAD

**Issue by youngToMaturity** [adfit/adfit-ios-sdk#39]
안녕하세요

cocoapod을 이용해 AdFitSDK의 버전을 올리는 과정에서
`Reference to 'SDAnimatedImageProvider' is ambiguous` 오류가 발생하여 문의 드립니다.

3.12.5까지는 정상 장동하는 것으로 보아 3.12.6에 추가된 `AFSDAnimatedImage.h`와 연관이 있어보이는데 해결방법이 있을까요?

```
Installing AdFitSDK (3.12.5)
...
Installing FLAnimatedImage (1.0.16)
Installing SDWebImage (5.11.1)
Installing SDWebImageFLPlugin (0.5.0)
```
정상 작동

```
Installing AdFitSDK (3.12.6)
...
Installing FLAnimatedImage (1.0.16)
Installing SDWebImage (5.11.1)
Installing SDWebImageFLPlugin (0.5.0)
```
오류 발생, 3.12.6~3.12.19 같은 오류 발생합니다.
iOS Deployment Target 13.0 입니다.

**Comment by Kim-Deogwon** [comment]
> 안녕하세요
> 
> cocoapod을 이용해 AdFitSDK의 버전을 올리는 과정에서 `Reference to 'SDAnimatedImageProvider' is ambiguous` 오류가 발생하여 문의 드립니다.
> 
> 3.12.5까지는 정상 장동하는 것으로 보아 3.12.6에 추가된 `AFSDAnimatedImage.h`와 연관이 있어보이는데 해결방법이 있을까요?
> 
> ```
> Installing AdFitSDK (3.12.5)
> ...
> Installing FLAnimatedImage (1.0.16)
> Installing SDWebImage (5.11.1)
> Installing SDWebImageFLPlugin (0.5.0)
> ```
> 
> 정상 작동
> 
> ```
> Installing AdFitSDK (3.12.6)
> ...
> Installing FLAnimatedImage (1.0.16)
> Installing SDWebImage (5.11.1)
> Installing SDWebImageFLPlugin (0.5.0)
> ```
> 
> 오류 발생, 3.12.6~3.12.19 같은 오류 발생합니다. iOS Deployment Target 13.0 입니다.

안녕하세요. @youngToMaturity 

이슈 확인 후 수정하여 배포 하도록 하겠습니다.

**Comment by Kim-Deogwon** [comment]
> 안녕하세요
> 
> cocoapod을 이용해 AdFitSDK의 버전을 올리는 과정에서 `Reference to 'SDAnimatedImageProvider' is ambiguous` 오류가 발생하여 문의 드립니다.
> 
> 3.12.5까지는 정상 장동하는 것으로 보아 3.12.6에 추가된 `AFSDAnimatedImage.h`와 연관이 있어보이는데 해결방법이 있을까요?
> 
> ```
> Installing AdFitSDK (3.12.5)
> ...
> Installing FLAnimatedImage (1.0.16)
> Installing SDWebImage (5.11.1)
> Installing SDWebImageFLPlugin (0.5.0)
> ```
> 
> 정상 작동
> 
> ```
> Installing AdFitSDK (3.12.6)
> ...
> Installing FLAnimatedImage (1.0.16)
> Installing SDWebImage (5.11.1)
> Installing SDWebImageFLPlugin (0.5.0)
> ```
> 
> 오류 발생, 3.12.6~3.12.19 같은 오류 발생합니다. iOS Deployment Target 13.0 입니다.

@youngToMaturity 

이슈 수정하여 3.12.21 버전으로 배포 하였습니다. 

한번 확인 해보시겠어요? 혹시 가능하시면 결과 공유도 같이 부탁 드릴께요.

감사합니다.

**Comment by youngToMaturity** [comment]
네 3.12.21 버전 적용 후 정상적으로 작동합니다.

이슈 닫도록 하겠습니다.

감사합니다!
