### ISSUE TITLE
pod install LICENSE.txt 파일 관련 워닝

### ISSUE THREAD

**Issue by xpdlf1004** [adfit/adfit-ios-sdk#40]
안녕하세요.

cocoaPod, AdFitSDK(3.12.21)로 설치를 하려고 하는데
pod install 시 아래와 같은 워닝이 뜨네요. 워닝이라 상관없지만 수정되면 더 좋을 것 같습니다. :)

```
[!] Unable to read the license file `LICENSE.txt` for the spec `AdFitSDK (3.12.21)`
```

**Comment by Kim-Deogwon** [comment]
> 안녕하세요.
> 
> cocoaPod, AdFitSDK(3.12.21)로 설치를 하려고 하는데 pod install 시 아래와 같은 워닝이 뜨네요. 워닝이라 상관없지만 수정되면 더 좋을 것 같습니다. :)
> 
> ```
> [!] Unable to read the license file `LICENSE.txt` for the spec `AdFitSDK (3.12.21)`
> ```

안녕하세요. 

3.12.22 버전으로 해당 이슈 수정하여 배포 하였습니다. 

감사합니다.

**Comment by xpdlf1004** [comment]
감사합니다 :)
