### ISSUE TITLE
아카이브 업로드 시 오류

### ISSUE THREAD

**Issue by yslee** [adfit/adfit-ios-sdk#41]
안녕하세요.
아카이브 업로드 시 아래와 같은 오류가 발생하는데요,

Asset validation failed
CFBundleIdentifier Collision. There is more than one bundle with the CFBundleIdentifier value 'com.kakao.biz.AdFitSDK' under the iOS application 'MyApp.app'.

이 경우는 MyApp에서 사용하는 여러 프레임워크 중 com.kakao.biz.AdFitSDK를 포함하는 프레임워크들이 여러 개 있다는 의미인가요?
그렇다면 어떻게 수정이 가능한지 문의드립니다.

**Comment by Kim-Deogwon** [comment]
> 안녕하세요. 아카이브 업로드 시 아래와 같은 오류가 발생하는데요,
> 
> Asset validation failed CFBundleIdentifier Collision. There is more than one bundle with the CFBundleIdentifier value 'com.kakao.biz.AdFitSDK' under the iOS application 'MyApp.app'.
> 
> 이 경우는 MyApp에서 사용하는 여러 프레임워크 중 com.kakao.biz.AdFitSDK를 포함하는 프레임워크들이 여러 개 있다는 의미인가요? 그렇다면 어떻게 수정이 가능한지 문의드립니다.

kyle.kao@kakaocorp.com 으로 메일 보내주세요. 
혹시 재현되는 프로젝트를 더미로 생성하여, 압축해서 보내주신다면 빠르게 문제점을 파악할 수 있는데 도움이 될 것 같습니다. 감사합니다.
