### ISSUE TITLE
배너 테스트 광고 클릭후  연결된 페이지에서 뒤로가기 제한됨

### ISSUE THREAD

**Issue by Marty-Kim** [adfit/adfit-ios-sdk#42]
배너광고를 눌러 광고주페이지로 이동하게되면 
풀스크린으로 화면이 발생되어 뒤로가기 불가능합니다 
Swipe To Rewind 도 안되고, 페이지내 뒤로가기 등이 없어 갇힘 현상이 발생중입니다.
어떻게 조치해야할까요 ?
`

             let bannerAdView = AdFitBannerAdView(clientId: AdProps.MAIN_BANNER_ADID, adUnitSize: "320x50")
             bannerAdView.frame = CGRect(x: 0, y: 0, width: self.adView.bounds.width, height: 50)

             bannerAdView.rootViewController = self
             bannerAdView.delegate = self
                      
             self.adView.addSubview(bannerAdView)
             bannerAdView.loadAd()

`

**Comment by Marty-Kim** [comment]
https://user-images.githubusercontent.com/22796515/233314259-b17eea90-83f9-4bce-82c7-19e75c480b3a.mp4

**Comment by Kim-Deogwon** [comment]
@Marty-Kim 

안녕하세요.

현재 네비게이션 바가 보이지 않는것 같아 보입니다. 

safeArea 밖으로 네비게이션바가 나가 있는 상황인지, 숨겨져 있어서 안보이는 상황인지 확인 해봐야 할것 같습니다. 

<img width="1350" alt="CS1" src="https://user-images.githubusercontent.com/29156246/234510969-61757c69-00bd-4c77-97dc-9fe2bea8fac5.png">

혹시 위에 첨부드린 이미지와 같이, 시뮬레이터에서 뷰하이에라키를 캡쳐하셔서 네비게이션 바의 정보를 확인 해 주실수 있을까요?

혹은 해당 현상이 재현되는 샘플을 제공 해주신다면 이슈 해결에 도움이 될 것 같습니다. 

감사합니다.

**Comment by Marty-Kim** [comment]
현재 UINavigation Bar를 hidden 처리하여 사용하고 있지 않습니다 
navBar hidden 을 하게되면 위와같은 상황이발생되는 걸까요 ?

**Comment by Kim-Deogwon** [comment]
@Marty-Kim  

아니요. 
사용하시는 네비게이션 컨트롤러를 히든 처리 하신다고 해당 현상이 발생하지는 않습니다. 

지금까지 네비게이션바가 보이지 않는 현상이 없었던 상황이어서, 다양하게 확인 해보는 과정이라고 생각하시면 될 것 같습니다.

**Comment by Marty-Kim** [comment]
@Kim-Deogwon 
하이어라키를 봤을때 UINavigationBar가 존재하지 않습니다

**Comment by Kim-Deogwon** [comment]
@Marty-Kim 

- 랜딩이 된 상태에서 좌측 사이드바의 뷰 하이에라키 및 중간에 뷰 하이에라키를 캡쳐해서 주시면 추가적으로 분석 해보겠습니다. 
- 샘플앱을 받아보시고, 사용하고 계신 광고단위를 넣어 테스트 한번 부탁 드릴께요.


감사합니다.

**Comment by Marty-Kim** [comment]
사용중인 광고의 매체가 심사 거절이 되어 
해당 광고 단위로 테스트가 불가합니다..
어떻게 해야할까요 ?

**Comment by Kim-Deogwon** [comment]
@Marty-Kim 

심사 거절과 관련해서는 제가 더 이상 도와드릴 부분이 없을 것 같습니다. (노출과 관련된 기술적 문의만 해결 드릴 수 있음)

이후 다음 과정이 진행되었을 때 도와드릴 수 있을 것 같습니다. (심사 통과 이후)

감사합니다.
