### ISSUE TITLE
Xcode 15로 빌드후 무경설 오류 발생.

### ISSUE THREAD

**Issue by newhyunsu** [adfit/adfit-ios-sdk#45]
Xcode 15로 빌드후 arhcive 한 후 설치시에 무결성 오류가 발생됨. 

Adfit은 SPM을 사용하여 3.12.18을 사용하였고 그 이전에는 Cocoapod을 이용해 동일 버전을 사용했었습니다. 

에러 전문은 아래와 같습니다. 

> Error installing  '/Users/Documents/release/MyApp.ipa', ERROR: Error Domain=com.apple.dt.CoreDeviceError Code=3002 "Failed to install the app on the device." UserInfo={NSURL=file:///Users/Documents/release/MyApp.ipa, NSLocalizedDescription=Failed to install the app on the device., NSUnderlyingError=0x60003ac38f30 {Error Domain=IXUserPresentableErrorDomain Code=14 "‘MyApp’을(를) 설치할 수 없음" UserInfo={NSUnderlyingError=0x60003ac3a4f0 {Error Domain=MIInstallerErrorDomain Code=13 "Failed to verify code signature of /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.ywm68D/extracted/Payload/MyApp.app/Frameworks/AdFitSDK.framework : 0xe800801c (No code signature found.)" UserInfo={FunctionName=+[MICodeSigningVerifier _validateSignatureAndCopyInfoForURL:withOptions:error:], LegacyErrorString=ApplicationVerificationFailed, SourceFileLine=78, LibMISErrorNumber=-402620388, NSLocalizedDescription=Failed to verify code signature of /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.ywm68D/extracted/Payload/MyApp.app/Frameworks/AdFitSDK.framework : 0xe800801c (No code signature found.)}}, NSLocalizedDescription=‘MyApp’을(를) 설치할 수 없음, NSLocalizedRecoverySuggestion=Failed to verify code signature of /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.ywm68D/extracted/Payload/MyApp.app/Frameworks/AdFitSDK.framework : 0xe800801c (No code signature found.), NSLocalizedFailureReason=무결성을 확인할 수 없기 때문에 이 앱을 설치할 수 없습니다.}}}
> Domain: com.apple.dt.DVTCoreDevice
> Code: -1
> User Info: {
>     DVTErrorCreationDateKey = "2024-02-05 23:47:54 +0000";
> }
> --

System Information

macOS Version 14.3 (Build 23D56)
Xcode 15.2 (22503) (Build 15C500b)
Timestamp: 2024-02-06T08:47:54+09:00

**Comment by newhyunsu** [comment]
SPM에서 다시 Cocoapod으로 전환하여 무결성 문제 해결.

**Comment by beomkey-nkb** [comment]
@newhyunsu 안녕하세요? 해당 문제에 대해 3.14.12 버전에 수정하였습니다. 제보 감사드립니다.
