### ISSUE TITLE
배너 클릭후 광고 페이지로 진입시 다시 뒤로 돌아 올수 없는 이슈

### ISSUE THREAD

**Issue by Ron-jemin** [adfit/adfit-ios-sdk#47]
swiftUI 버전 비즈보드 배너광고 연동을 했는데요. 
배너는 잘 나오는것 확인했는데 광고 클릭했을때 
전체화면으로 광고페이지가 나와서 다시 뒤로 올수 없습니다.

코드상으로는 샘플에 있는 예제 그대로 사용하고있는데 광고 클릭했을때 다시 원래 화면으로 돌아오게 하려면 추가 작업이 필요한가요? 

현재 개발중인 앱 과 테스트용 샘플앱 의 View 하이라키를 비교했을때  UINavigationBar 라는 view 가 현재 개발중인 앱에는 안붙어있는것을 확인할 수 있는데..  혹시 도움 주실수 있을까요 ? 

<img width="928" alt="image" src="https://github.com/user-attachments/assets/3ec3a55e-f789-4560-b559-327ddb602ba3">

**Comment by beomkey-nkb** [comment]
안녕하세요 제보 감사합니다.
공유 주신 내용으론 정확한 원인을 파악하기엔 어려움이 있습니다. 
광고주 페이지로 이동 시, 상단에 X 버튼을 통해 이전 화면으로 되돌아 갈 수 있는데요
광고주 페이지에서 X버튼이 노출되지 않는 상황일까요?

문제가되는 화면의 스크린샷과 현재 사용 중인 SDK 버전을 공유해주시면 좀 더 빠른 문제 파악이 가능할 것 같습니다.
감사합니다.

**Comment by Ron-jemin** [comment]
https://github.com/user-attachments/assets/9220d799-1d07-4de2-be3a-76285be469a3

현재 사용하고 있는버전은 3.15.2 버전 사용하고 있습니다. 

영상에서 처럼 Info 버튼 눌렀을때 카카오광고 소개 페이지 뿐 아니라 광고주 페이지에서 X버튼이 노출 되고 있지 않습니다.

**Comment by beomkey-nkb** [comment]
@Ron-jemin 안녕하세요? 답변이 늦어 죄송합니다.

우선 영상 공유 감사드립니다. 이전에 질문 주셨던 부분들을 취합해보면,
SwiftUI 환경에서 작업하신걸로 파악되고, 영상을 봤을 때 AdFitBannerPresentableView를 사용한 것으로 추측됩니다.
저희 측에서는 보내주신 영상처럼 재현이 안돼서, 사용하신 쪽 코드를 직접 받아보면 원인 파악에 도움이 될 것 같습니다.

추가적으로
1. 영상에 달려있는 광고 이외의 다른 광고에도 동일 현상이 발생하는지
2. 광고를 붙이고자 하는 앱이 앱스토어에 출시되어 있다면 어떤 앱인지
3. 광고 뷰와 연관이 있는 뷰나 ViewController에서 navigation에 대해 제어하는 코드가 있는지

해당 부분들에 대해 공유해주시면 원인을 분석해보고 공유드리도록 하겠습니다. 감사합니다.
cc. @Kim-Deogwon

**Comment by Ron-jemin** [comment]
@beomkey-nkb 답변 감사드립니다. 
3. 광고 뷰와 연관이 있는 뷰나 ViewController에서 navigation에 대해 제어하는 코드가 있는지

adfit에서 어떻게 present로 광고주 페이지를 표시하는지 몰랐었는데 3번 부분 말씀해주셔서 
UINavigationController 커스텀 한부분이 있었는데 이부분 수정하니깐 상단 Navigation Bar 잘 나오네요 

앱 내에 코드 문제라서 close처리 하겠습니다.
