### ISSUE TITLE
adift-ios-sdk fail 콜백이 안오는데 이유를 알수 있나요?

### ISSUE THREAD

**Issue by newhyunsu** [adfit/adfit-ios-sdk#48]
현재 적용 버전은 3.14.20을 사용하고 있습니다. 
test 광고의 경우는 정상적으로 동작을 하는데, 
상용 환경에서 광고가 로드되지 않을경우에 Fail 콜백이 안오는걸로 보입니다.

**Comment by beomkey-nkb** [comment]
안녕하세요 제보 감사합니다.
어떤 유형의 광고를 사용 중인지 공유 부탁드립니다.

**Comment by beomkey-nkb** [comment]
답변이 없으셔서 해당 이슈는 close 처리 하겠습니다.
재현 시, 다시 문의 부탁드립니다.
감사합니다.
