### ISSUE TITLE
adfit  podfile에서 설치해서 사용하려고 하는데 crash 발생합니다.

### ISSUE THREAD

**Issue by DrummerKang** [adfit/adfit-ios-sdk#6]
가이드대로 했는데~ 어떤이유인지 잘 모르겠네요~

dyld: Library not loaded: @rpath/AdFitSDK.framework/AdFitSDK
  Referenced from: /var/containers/Bundle/Application/~~~
  Reason: image not found

**Comment by astrokil** [comment]
안녕하세요 AdFit iOS SDK 담당자입니다.
전해주신 정보만으로는 저희가 원인을 정확하게 파악하기 어렵습니다.
일단은 로컬의 AdFitSDK 팟의 캐시를 제거한 후 다시 install 해보시기 바랍니다. (프로젝트도 clean 시켜주세요)
가능하다면, [고객센터](https://cs.daum.net/question/1440.html)를 통해 해당 현상이 동일하게 일어나는 샘플 프로젝트를 공유해주세요.
그럼 저희가 더욱 정확한 해결 방법을 드릴 수 있을 것 같습니다.
감사합니다.

**Comment by pro76jp** [comment]
In the target's General tab, there is an Embedded Binaries field. When you add the framework there the crash is resolved.

I have also tried to change the "Embedded Content Contains Swift Code" flag to true in build settings
