### ISSUE TITLE
AdFitSDK.framework/strip-frameworks.sh: No such file or directory

### ISSUE THREAD

**Issue by jnukhj** [adfit/adfit-ios-sdk#8]
Xcode 9.3  // AdFitSDK 3.0.2

계속 아래와 같은 오류가 나고 있어서 문의드립니다.
AdFitSDK.framework/strip-frameworks.sh: No such file or directory

1. AdFitSDK 3.02 zip을 받아서 AdFitSDK.framework를 General > Embed Binaries에 끌어놓았습니다.
2. Build Phases > Run Script에 알려주신 bash 를 복사해서 작성했습니다.
3. BuildSetting > Always Embed ...  설정값을 YES로 변경했습니다.
4. AdFitSDK.framework 내부에 strip-frameworks.sh 파일이 있는것도 확인했습니다.

무엇이 문제일까요..
3.0.0 버전으로 잘 쓰고 있다가, 3.0.2로 업데이트 하려고하니 오류가 발생하고 있습니다.

**Comment by Kim-Deogwon** [comment]
안녕하세요. AdFit 담당자 입니다.
불편을 드려 죄송합니다. 최신 Xcode 환경에서 옵션이 변경된 것 같습니다. 

아래와 같은 추가 작업을 부탁드립니다.

Run Script 에 bash를 복사해 준 후 'Run script only when installing' 항목의 옵션을 체크해주세요. 

감사합니다.

**Comment by jnukhj** [comment]
감사합니다.
해결되었습니다.
