### ISSUE TITLE
#8 에 대한 추가 오류 문의입니다.

### ISSUE THREAD

**Issue by jnukhj** [adfit/adfit-ios-sdk#9]
iOS 기기를 개발환경에 직접 연결하여 Build > Run 하면 오류는 없습니다.

개발된 앱을 배포하려고 Xcode > Product > Archive를 진행하면, 
동일한 오류가 발생됩니다.

**Comment by Kim-Deogwon** [comment]
안녕하세요. AdFit 담당자 입니다.

다시 한번 불편을 드려 죄송합니다. 

스크립트에서 Framework를 찾지 못해 에러가 나는 상황입니다. 

Framework 를 복사하는 작업이 스크립트를 수행 하는 작업 보다 먼저 이루어 져야 합니다. 

아래와 같은 작업을 부탁드립니다.

 `Run Script` 항목은 `Embed Frameworks` 항목 보다 아래에 위치해 있어야 합니다. 항목의 순서는 Drag&Drop 을 통해 변경할 수 있습니다. 

어제 말씀드렸던 아래 작업은 다시 비활성화 시켜도 동작을 하는 것 같습니다.

`Run Script` 에 bash를 복사해 준 후 'Run script only when installing' 항목의 옵션을 체크해주세요.

감사합니다.

*

**Comment by jnukhj** [comment]
아. 순서도 중요하군요. 
오늘 하나 더 배워갑니다.
감사합니다. 해당 증상은 해결되었습니다.
